### ISSUE TITLE
stat(density) deprecated warning

### ISSUE THREAD

**Issue by mbassalbioinformatics** [huklein/demuxmix#10]
Hi

In running demuxmix, you get the following error when running 

demuxmix::plotDmmHistogram(dmm)

```
Warning message:
`stat(density)` was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.
```

**Comment by huklein** [comment]
Hi,

Thanks for reporting. This warning should be gone when you install demuxmix version 1.1.1 or newer. You can install it either here from github or download the package from the Bioconductor development page:
https://bioconductor.org/packages/devel/bioc/html/demuxmix.html

Or just ignore the warning and wait until 1.1.1 becomes stable in a few months.

Best,
Hans

PS: Please let me know if you still get this warning with the newest version.
